import { Router } from "express";
import { AuthRouters } from "../module/auth/auth.route";
import { UserRoutes } from "../module/user/user.route";
import { AdminRoutes } from "../module/admin/admin.route";
import { CategoryRoutes } from "../module/category/category.route";
import { MedicineRoutes } from "../module/medicine/medicine.route";
import { OrderRoutes } from "../module/order/order.route";
const router=Router();
 router.use("/auth", AuthRouters);
 router.use("/users", UserRoutes); 
 router.use("/admin", AdminRoutes);
 router.use("/categories", CategoryRoutes);
 router.use("/medicines", MedicineRoutes);
 router.use("/orders", OrderRoutes);
 export const IndexRoutes=router;