import { Router } from "express";
import { AuthRouters } from "../module/auth/auth.route";
import { UserRoutes } from "../module/user/user.route";
import { AdminRoutes } from "../module/admin/admin.route";
import { CategoryRoutes } from "../module/category/category.route";
const router=Router();
 router.use("/auth", AuthRouters);
 router.use("/users", UserRoutes); 
 router.use("/admin", AdminRoutes);
 router.use("/categories", CategoryRoutes);
 export const IndexRoutes=router;